### ISSUE TITLE
Compass rose not rendered

### ISSUE THREAD

**Issue by Talkless** [hholzgra/ocitysmap#103]
I've generated map with `Compass-Rose-Overlay, Scale-Bar-Overlay, UTM-Grid-Overlay, ContourOverlay, ContourOverlay100`, but I don't see any "compass rose" on it:

https://print.get-map.org/maps/304086/olOVHaNxoKRdHSNb

**Comment by hholzgra** [comment]
It turned out that several overlay plugins had position offset calculations that were far from perfect, most it them should be fixed now.

Remaining problems:

* Multi page title page overview map is not at the top, smaller, and with wider side margins as the other maps, making things end up in completely wrong places -> overlay plugins completely disabled there for now. Aside from the surveillance and maybe the UTM grid plugins most of the effect plugins do not make sense that much on the smaller overview anyway ...

* Compass rose correctly shows on the large overview map on page iii correctly now, as do the surveillance cameras, but the scale bar is not visible for whatever reason. Not much of an issue though as it's only really of use on the detail pages anyway, where it correctly shows now

**Comment by hholzgra** [comment]
Remaining problems now tracked in #104

**Comment by Talkless** [comment]
Thanks @hholzgra !
